/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountCreate: typeof import('./components/AccountCreate.vue')['default']
    AccountPanel: typeof import('./components/AccountPanel.vue')['default']
    AssertPanel: typeof import('./components/AssertPanel.vue')['default']
    InitLoading: typeof import('./components/InitLoading.vue')['default']
    LogoImg: typeof import('./components/LogoImg.vue')['default']
    MainPageActs: typeof import('./components/MainPageActs.vue')['default']
    PasskeyModal: typeof import('./components/PasskeyModal.vue')['default']
    PassMintPanel: typeof import('./components/PassMintPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialMediaConnectList: typeof import('./components/SocialMediaConnectList.vue')['default']
  }
}
